# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.define :proxy do |proxy|
      proxy.vm.box = "debian/bookworm64"
      proxy.vm.hostname = "proxy"
      proxy.vm.synced_folder ".", "/vagrant", disabled: true
      proxy.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.0.0.1",
          :libvirt__forward_mode => "veryisolated"
      proxy.vm.provision "shell", run: "always", inline: <<-SHELL
        apt-get update #&& apt-get upgrade -y
        apt-get install apache2 -y
        sysctl -w net.ipv4.ip_forward=1
        iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -j MASQUERADE
        echo "10.0.0.2 interno.example.org" >> /etc/hosts
      SHELL
    end
    config.vm.define :backend do |backend|
      backend.vm.box = "debian/bookworm64"
      backend.vm.hostname = "backend"
      backend.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.0.0.2",
          :libvirt__forward_mode => "veryisolated"
      backend.vm.provision "shell", run: "always", inline: <<-SHELL
          ip r del default
          ip r add default via 10.0.0.1
          apt-get update #&& apt-get upgrade -y
          apt-get install apache2 -y
          cp /vagrant/ficheros/index.html /var/www/html
          cp /vagrant/ficheros/img.jpg /var/www/html
          cp /vagrant/ficheros/htaccess /var/www/html/.htaccess
          cp -r /vagrant/ficheros/carpeta /var/www/html
          cp -r /vagrant/ficheros/nuevodirectorio /var/www/html
          chown -R www-data: /var/www/html/
          cp /vagrant/ficheros/apache2.conf /etc/apache2
          systemctl restart apache2
      
      SHELL
    end
    
  end
