# Module: apache
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-apache.html
- module: apache
  metricsets:
    - status
  period: 10s
  hosts: ["http://127.0.0.1"]
  server_status_path: "server-status"
